version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - org-global

jobs:
  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo $MY_ENV_VAR
